

services:
#  MySQL configs
  mysql-enaa-auth-app:
    image: mysql
    container_name: mysql-enaa-auth-app-container
    ports:
      - "3307:3306"
    networks:
      - enaa-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: enaa_app_auth_db
    volumes:
      - mysql_auth_data:/var/lib/mysql

  mysql-enaa-briefing-app:
    image: mysql
    container_name: mysql-enaa-briefing-app-container
    ports:
      - "3308:3306"
    networks:
      - enaa-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: enaa_app_briefing_db
    volumes:
      - mysql_briefing_data:/var/lib/mysql

  mysql-enaa-skill-app:
    image: mysql
    container_name: mysql-enaa-skill-app-container
    ports:
      - "3309:3306"
    networks:
      - enaa-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: enaa_app_skill_db
    volumes:
      - mysql_skill_data:/var/lib/mysql

  mysql-enaa-validation-app:
    image: mysql
    container_name: mysql-enaa-validation-app-container
    ports:
      - "3310:3306"
    networks:
      - enaa-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: enaa_app_validation_db
    volumes:
      - mysql_validation_data:/var/lib/mysql



#  Micorservices configs
  eureka:
    build:
      context: ./eureka
    image: enaa-eureka
    container_name: enaa-eureka-container
    ports:
      - "8761:8761"
    networks:
      - enaa-net

  api-gateway:
    build:
      context: ./api-gateway
    image: enaa-api-gateway-img
    container_name: api-gateway-container
    ports:
      - "8088:8088"
    depends_on:
      - eureka
    networks:
      - enaa-net
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  auth-service:
    build:
      context: ./auth-service
    image: enaa-auth-service
    container_name: enaa-auth-service-container
    ports:
      - "8085:8085"
    depends_on:
      - mysql-enaa-auth-app
      - eureka
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-enaa-auth-app:3306/enaa_app_auth_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  briefing-service:
    build:
      context: ./briefing-service
    image: enaa-briefing-service
    container_name: enaa-briefing-service-container
    ports:
      - "8081:8081"
    depends_on:
      - mysql-enaa-briefing-app
      - eureka
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-enaa-briefing-app:3306/enaa_app_briefing_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  skill-service:
    build:
      context: ./skill-service
    image: enaa-skill-service
    container_name: enaa-skill-service-container
    ports:
      - "8082:8082"
    depends_on:
      - mysql-enaa-skill-app
      - eureka
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-enaa-skill-app:3306/enaa_app_skill_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  validation-service:
    build:
      context: ./validation-service
    image: enaa-validation-service
    container_name: enaa-validation-service-container
    ports:
      - "8083:8083"
    depends_on:
      - mysql-enaa-validation-app
      - eureka
    networks:
      - enaa-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-enaa-validation-app:3306/enaa_app_validation_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka


networks:
  enaa-net:
    driver: bridge

volumes:
  mysql_auth_data:
  mysql_briefing_data:
  mysql_skill_data:
  mysql_validation_data:












