version: "3.9"

services:

  mysql:
    image: mysql
    container_name: mysql-enaa-skills-app
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: enaa_app_skills_db
    networks:
      - enaa-network

  skill-service:
    image: enaa-skills-app-img
    container_name: enaa-skills-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - enaa-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-enaa-skills-app:3306/enaa_app_skills_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  enaa-network:
    driver: bridge
