server:
  port: 8088

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: validation-route
          uri: lb://VALIDATION-SERVICE
          predicates:
            - Path=/validation/**
          filters:
            - StripPrefix=1

        - id: briefing-route
          uri: lb://BRIEFING-SERVICE
          predicates:
            - Path=/briefing/**
          filters:
            - StripPrefix=1

        - id: skill-route
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/skill/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka